[package]
name = "link-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
reqwest = { version = "0.12.9", features = ["blocking", "rustls-tls"] }
scraper = "0.21.0"
thiserror = "2.0.3"
